### ISSUE TITLE
The template "to_qtl" doesn't exist

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-beanmine#1]
The template "to_qtl" doesn't exist! (link from home page not working- probably you forgot to
tag it for your adoring im:public or something?)

**Comment by adf-ncgr** [comment]
looks like the link from the front page uses scope=user instead of scope=all
the link from the actual templates page formulated as:
https://mines.legumeinfo.org/beanmine/template.do?name=to_qtl&scope=all
works fine

**Comment by sammyjava** [comment]
Interesting, never noticed that. It's updated, I'm re-indexing beanmine, so after that's done I'll rebuild the webapp and the link should work. It worked for me, of course, since I was logged in, I guess.
