### ISSUE TITLE
Lack of data for some TO terms

### ISSUE THREAD

**Issue by sammyjava** [LegumeFederation/intermine-beanmine#2]
Very weird bug: even though the data is complete in the database, some TO terms are showing nearly empty on the mine. For example:
https://mines.legumeinfo.org/beanmine/report.do?id=17000039
That term is completely populated in the DB. Rebuilding indexes didn't help.

**Comment by adf-ncgr** [comment]
I suspect this is unrelated, but I noticed that the example search on cowpeamine "Flower color" returns TO terms, but none are linked to actual QTLs; guessing that this is because we no longer have the relevant QTLs though. Didn't seem worth making an issue out of- but mentioning here just in case.

**Comment by sammyjava** [comment]
Yeah, this is all we have now:
```

ame
--
Adventitious root angle (manual)
Avg root density (DIRT)
Basal root angle (manual)
CPD 25 (DIRT)
CPD75 (DIRT)
D10 (DIRT)
D20 (DIRT)
D50 (DIRT)
D60 (DIRT)
Hls
Max root width (DIRT)
Median root width (DIRT)
QAc-vu1.1
QAc-vu7.1
QRk-vu11.1
Qpl.zaas-3
Qpl.zaas-5
RTA range (DIRT)
Stem diameter (DIRT)
Stem diameter (manual)
TD10 (manual)
TD15 (manual)
```

**Comment by sammyjava** [comment]
This seems to have been resolved. There are 123 TO terms which do not have descriptions, which is legit; only two have no name, also legit.
