### ISSUE TITLE
beanmine returns error at home page

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-beanmine#4]
https://mines.legumeinfo.org/beanmine/begin.do

There has been an internal error while processing your request. The problem has been logged and will be investigated. You may also send us an email describing how you encountered this error.
The problem may be temporary in which case you might wish to go back and try your request again or you might want to go to the home page.

tried several refreshes. Report pages show similar behavior, though it doesn't appear to affect some info from being returned, e.g.:
https://mines.legumeinfo.org/beanmine/report.do?id=6047700

**Comment by adf-ncgr** [comment]
I'm going to let this one issue stand for all the species-specific mines, which all seem to be exhibiting the same behavior at this time, so probably fix whatever underlies and you fix them all?

**Comment by sammyjava** [comment]
I think this was a Tomcat restart or something. Anyway, gone.
