### ISSUE TITLE
beanmine pathways give bad shareable links

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-beanmine#7]
e.g. 
https://mines.legumeinfo.org/beanminenull
is the shareable link given for 
https://mines.legumeinfo.org/beanmine/report.do?id=12000135

not exactly a crisis. it may affect other mines too, but this is where I discovered it and I'm too lazy to look further

**Comment by sammyjava** [comment]
Fixed. Had to add some stuff to the class keys file.
